# Generated by Django 6.1.1 on 2026-09-22 00:20

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_previa', models.UUIDField(unique=True)),
                ('concluida_em', models.DateTimeField()),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('tamanho_arquivo', models.PositiveBigIntegerField()),
                ('sha256_arquivo', models.CharField(max_length=64)),
                ('total_recebidos', models.PositiveIntegerField()),
                ('total_inseridos', models.PositiveIntegerField()),
                ('total_atualizados', models.PositiveIntegerField()),
                ('total_atualizados_com_alteracao', models.PositiveIntegerField()),
                ('total_rejeitados', models.PositiveIntegerField()),
                ('total_divergencias', models.PositiveIntegerField()),
                ('total_ausentes_no_arquivo', models.PositiveIntegerField()),
                ('executada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-concluida_em'],
            },
        ),
        migrations.CreateModel(
            name='ExcecaoImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha_inicial', models.PositiveIntegerField()),
                ('linha_final', models.PositiveIntegerField()),
                ('cadpro', models.TextField(blank=True)),
                ('motivo', models.CharField(choices=[('LINHA_NAO_ASSOCIAVEL', 'Linha não associável a nenhum registro'), ('ESTRUTURA_INCONSISTENTE', 'Estrutura do registro inconsistente'), ('CADPRO_AUSENTE', 'Código (CADPRO) ausente'), ('CADPRO_FORMATO_INVALIDO', 'Código (CADPRO) em formato inválido'), ('CADPRO_DUPLICADO_NO_ARQUIVO', 'Código (CADPRO) duplicado no arquivo'), ('DESCRICAO_AUSENTE', 'Descrição ausente'), ('UNIDADE_AUSENTE', 'Unidade ausente'), ('QUANTIDADE_AUSENTE', 'Quantidade ausente'), ('QUANTIDADE_NAO_NUMERICA', 'Quantidade não numérica'), ('QUANTIDADE_NEGATIVA', 'Quantidade negativa'), ('QUANTIDADE_FORA_DO_LIMITE', 'Quantidade fora do limite de dígitos')])),
                ('detalhe', models.TextField(blank=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excecoes', to='catalogo.execucaoimportacao')),
            ],
            options={
                'ordering': ['linha_inicial'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadpro', models.CharField(editable=False, max_length=11)),
                ('descricao', models.TextField()),
                ('descricao_busca', models.TextField()),
                ('unidade', models.TextField()),
                ('detalhamento', models.TextField(blank=True)),
                ('grupo', models.TextField(blank=True)),
                ('subgrupo', models.TextField(blank=True)),
                ('nome_grupo', models.TextField(blank=True)),
                ('nome_subgrupo', models.TextField(blank=True)),
                ('saldo', models.DecimalField(decimal_places=3, max_digits=15)),
                ('saldo_inicial', models.DecimalField(decimal_places=3, editable=False, max_digits=15)),
                ('execucao_origem', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='catalogo.execucaoimportacao')),
            ],
            options={
                'ordering': ['cadpro'],
            },
        ),
        migrations.CreateModel(
            name='DivergenciaSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_wms', models.DecimalField(decimal_places=3, max_digits=15)),
                ('saldo_arquivo', models.DecimalField(decimal_places=3, max_digits=15)),
                ('diferenca', models.DecimalField(decimal_places=3, max_digits=16)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divergencias', to='catalogo.execucaoimportacao')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.material')),
            ],
            options={
                'ordering': ['material__cadpro'],
            },
        ),
        migrations.CreateModel(
            name='AlteracaoCadastralMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('descricao', 'Descrição'), ('unidade', 'Unidade'), ('detalhamento', 'Detalhamento'), ('grupo', 'Grupo'), ('subgrupo', 'Subgrupo'), ('nome_grupo', 'Nome do grupo'), ('nome_subgrupo', 'Nome do subgrupo')])),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_novo', models.TextField(blank=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes', to='catalogo.execucaoimportacao')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.material')),
            ],
        ),
        migrations.AddConstraint(
            model_name='execucaoimportacao',
            constraint=models.CheckConstraint(condition=models.Q(('total_recebidos', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('total_inseridos'), '+', models.F('total_atualizados')), '+', models.F('total_rejeitados')))), name='catalogo_execucaoimportacao_totais_ok'),
        ),
        migrations.AddConstraint(
            model_name='execucaoimportacao',
            constraint=models.CheckConstraint(condition=models.Q(('total_atualizados_com_alteracao__lte', models.F('total_atualizados'))), name='catalogo_execucaoimportacao_atualizados_alteracao_max'),
        ),
        migrations.AddConstraint(
            model_name='excecaoimportacao',
            constraint=models.CheckConstraint(condition=models.Q(('linha_final__gte', models.F('linha_inicial'))), name='catalogo_excecaoimportacao_linha_final_gte_inicial'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=django.contrib.postgres.indexes.GinIndex(fields=['descricao_busca'], name='catalogo_material_busca_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('cadpro',), name='catalogo_material_cadpro_unico'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('cadpro__regex', '^[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}$')), name='catalogo_material_cadpro_formato'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('saldo__gte', 0)), name='catalogo_material_saldo_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_inicial__gte', 0)), name='catalogo_material_saldo_inicial_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='divergenciasaldo',
            constraint=models.UniqueConstraint(fields=('execucao', 'material'), name='catalogo_divergenciasaldo_unico_execucao_material'),
        ),
        migrations.AddConstraint(
            model_name='divergenciasaldo',
            constraint=models.CheckConstraint(condition=models.Q(('diferenca', django.db.models.expressions.CombinedExpression(models.F('saldo_arquivo'), '-', models.F('saldo_wms')))), name='catalogo_divergenciasaldo_diferenca_calculo'),
        ),
        migrations.AddConstraint(
            model_name='divergenciasaldo',
            constraint=models.CheckConstraint(condition=models.Q(('diferenca', 0), _negated=True), name='catalogo_divergenciasaldo_diferenca_nao_zero'),
        ),
        migrations.AddConstraint(
            model_name='alteracaocadastralmaterial',
            constraint=models.UniqueConstraint(fields=('execucao', 'material', 'campo'), name='catalogo_alteracaocadastral_unico_execucao_material_campo'),
        ),
        migrations.AddConstraint(
            model_name='alteracaocadastralmaterial',
            constraint=models.CheckConstraint(condition=models.Q(('valor_anterior', models.F('valor_novo')), _negated=True), name='catalogo_alteracaocadastral_valor_alterado'),
        ),
    ]
