# Generated by Django 6.1.1 on 2026-09-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
